services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3001:3000'
    depends_on:
      - db
      - redis
    env_file:
      - ./.env
    networks:
      - default

  db:
    image: postgis/postgis:latest
    restart: always
    ports:
      - '5433:5432'
    environment:
      - POSTGRES_USER="root"
      - POSTGRES_PASSWORD="Password123!"
      - POSTGRES_DB="booking"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - default

  redis:
    image: redis:7
    restart: always
    ports:
      - '6380:6379'
    volumes:
      - redis-data:/data
    networks:
      - default

volumes:
  postgres-data:
  redis-data:

networks:
  default:
    driver: bridge
